name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Test the application
        run: |
          docker-compose up -d
          sleep 10 # Wait for services to start
          curl --retry 5 --retry-delay 5 http://localhost:3000 || exit 1
          docker-compose down